all:
  children:
    k8s_nodes:
      children:
        masters:
          hosts:
            localhost:
              ansible_connection: local
              node_role: master
  vars:
    ansible_user: ubuntu
    ansible_python_interpreter: /usr/bin/python3
