---
- name: Restart microk8s
  ansible.builtin.command: microk8s stop && microk8s start
  changed_when: true

- name: Refresh microk8s config
  ansible.builtin.shell: microk8s config > {{ kubeconfig_dir }}/config
  changed_when: true
