---
- name: Restart k3s
  ansible.builtin.systemd:
    name: k3s
    state: restarted
    enabled: true
    daemon_reload: true

- name: Restart k3s-agent
  ansible.builtin.systemd:
    name: k3s-agent
    state: restarted
    enabled: true
    daemon_reload: true
