{
 "title": "Knative Serving - Control Plane Efficiency - nuc6",
 "description": "Dashboard for Knative Serving Control Plane Efficiency\n(https://github.com/knative/serving)\n",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "source", "label": "Source", "query": "label_values(up, source)" }
  ]
 },
 "panels": [
  { "title": "Activator", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of each running instance",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{container=\"activator\",source=\"$source\",namespace=\"knative-serving\",pod=~\"activator-.*\"}[$__rate_interval]))",
     "legendFormat": "Container ({{pod}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of each running instance",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{container=\"activator\",source=\"$source\",namespace=\"knative-serving\",pod=~\"activator-.*\"})",
     "legendFormat": "Container ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memory_used_bytes{go_memory_type=\"stack\",source=\"$source\",namespace=\"knative-serving\",pod=~\"activator-.*\"})",
     "legendFormat": "Stack ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memory_used_bytes{go_memory_type=\"other\",source=\"$source\",namespace=\"knative-serving\",pod=~\"activator-.*\"})",
     "legendFormat": "Heap (In Use) ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memstats_heap_alloc_bytes{namespace=\"knative-serving\",source=\"$source\",pod=~\"activator-.*\"})",
     "legendFormat": "Heap (Allocated) ({{pod}})"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "timeseries",
   "description": "Details about memory allocations",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(go_memory_allocated_bytes_total{namespace=\"knative-serving\",source=\"$source\",pod=~\"activator-.*\"}[$__rate_interval]))",
     "legendFormat": "Bytes ({{pod}})"
    },
    {
     "expr": "sum by (pod) (rate(go_memory_allocations_total{namespace=\"knative-serving\",source=\"$source\",pod=~\"activator-.*\"}[$__rate_interval]))",
     "legendFormat": "Objects ({{pod}})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Goroutine count for each running instance",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (go_goroutine_count{namespace=\"knative-serving\",source=\"$source\",pod=~\"activator-.*\"})",
     "legendFormat": "Goroutines ({{pod}})"
    }
   ]
  },
  { "title": "Autoscaler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of each running instance",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{container=\"autoscaler\",namespace=\"knative-serving\",source=\"$source\",pod=~\"autoscaler-.*\"}[$__rate_interval]))",
     "legendFormat": "Container ({{pod}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of each running instance",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{container=\"autoscaler\",source=\"$source\",namespace=\"knative-serving\",pod=~\"autoscaler-.*\"})",
     "legendFormat": "Container ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memory_used_bytes{go_memory_type=\"stack\",source=\"$source\",namespace=\"knative-serving\",pod=~\"autoscaler-.*\"})",
     "legendFormat": "Stack ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memory_used_bytes{go_memory_type=\"other\",source=\"$source\",namespace=\"knative-serving\",pod=~\"autoscaler-.*\"})",
     "legendFormat": "Heap (In Use) ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memstats_heap_alloc_bytes{namespace=\"knative-serving\",source=\"$source\",pod=~\"autoscaler-.*\"})",
     "legendFormat": "Heap (Allocated) ({{pod}})"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "timeseries",
   "description": "Details about memory allocations",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(go_memory_allocated_bytes_total{namespace=\"knative-serving\",source=\"$source\",pod=~\"autoscaler-.*\"}[$__rate_interval]))",
     "legendFormat": "Bytes ({{pod}})"
    },
    {
     "expr": "sum by (pod) (rate(go_memory_allocations_total{namespace=\"knative-serving\",source=\"$source\",pod=~\"autoscaler-.*\"}[$__rate_interval]))",
     "legendFormat": "Objects ({{pod}})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Goroutine count for each running instance",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (go_goroutine_count{namespace=\"knative-serving\",source=\"$source\",pod=~\"autoscaler-.*\"})",
     "legendFormat": "Goroutines ({{pod}})"
    }
   ]
  },
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of each running instance",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{container=\"controller\",namespace=\"knative-serving\",source=\"$source\",pod=~\"controller-.*\"}[$__rate_interval]))",
     "legendFormat": "Container ({{pod}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of each running instance",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{container=\"controller\",namespace=\"knative-serving\",source=\"$source\",pod=~\"controller-.*\"})",
     "legendFormat": "Container ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memory_used_bytes{go_memory_type=\"stack\",namespace=\"knative-serving\",source=\"$source\",pod=~\"controller-.*\"})",
     "legendFormat": "Stack ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memory_used_bytes{go_memory_type=\"other\",namespace=\"knative-serving\",source=\"$source\",pod=~\"controller-.*\"})",
     "legendFormat": "Heap (In Use) ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memstats_heap_alloc_bytes{namespace=\"knative-serving\",source=\"$source\",pod=~\"controller-.*\"})",
     "legendFormat": "Heap (Allocated) ({{pod}})"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "timeseries",
   "description": "Details about memory allocations",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(go_memory_allocated_bytes_total{namespace=\"knative-serving\",source=\"$source\",pod=~\"controller-.*\"}[$__rate_interval]))",
     "legendFormat": "Bytes ({{pod}})"
    },
    {
     "expr": "sum by (pod) (rate(go_memory_allocations_total{namespace=\"knative-serving\",source=\"$source\",pod=~\"controller-.*\"}[$__rate_interval]))",
     "legendFormat": "Objects ({{pod}})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Goroutine count for each running instance",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (go_goroutine_count{namespace=\"knative-serving\",source=\"$source\",pod=~\"controller-.*\"})",
     "legendFormat": "Goroutines ({{pod}})"
    }
   ]
  },
  { "title": "Webhook", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of each running instance",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by (pod) (irate(container_cpu_usage_seconds_total{container=\"webhook\",namespace=\"knative-serving\",source=\"$source\",pod=~\"webhook-.*\"}[$__rate_interval]))",
     "legendFormat": "Container ({{pod}})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage of each running instance",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{container=\"webhook\",namespace=\"knative-serving\",source=\"$source\",pod=~\"webhook-.*\"})",
     "legendFormat": "Container ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memory_used_bytes{go_memory_type=\"stack\",namespace=\"knative-serving\",source=\"$source\",pod=~\"webhook-.*\"})",
     "legendFormat": "Stack ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memory_used_bytes{go_memory_type=\"other\",source=\"$source\",namespace=\"knative-serving\",pod=~\"webhook-.*\"})",
     "legendFormat": "Heap (In Use) ({{pod}})"
    },
    {
     "expr": "sum by (pod) (go_memstats_heap_alloc_bytes{namespace=\"knative-serving\",source=\"$source\",pod=~\"webhook-.*\"})",
     "legendFormat": "Heap (Allocated) ({{pod}})"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "timeseries",
   "description": "Details about memory allocations",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(go_memory_allocated_bytes_total{namespace=\"knative-serving\",source=\"$source\",pod=~\"webhook-.*\"}[$__rate_interval]))",
     "legendFormat": "Bytes ({{pod}})"
    },
    {
     "expr": "sum by (pod) (rate(go_memory_allocations_total{namespace=\"knative-serving\",source=\"$source\",pod=~\"webhook-.*\"}[$__rate_interval]))",
     "legendFormat": "Objects ({{pod}})"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "description": "Goroutine count for each running instance",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (go_goroutine_count{namespace=\"knative-serving\",source=\"$source\",pod=~\"webhook-.*\"})",
     "legendFormat": "Goroutines ({{pod}})"
    }
   ]
  }
 ]
}